# Generated by Django 5.2.6 on 2025-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_comp', models.IntegerField()),
                ('fecha_hs_comp', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetCompras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'det_compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'productos_x_proveedores',
                'managed': True,
            },
        ),
    ]
