# Generated by Django 5.2.6 on 2025-11-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_comp', models.IntegerField()),
                ('fecha_hs_comp', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=9)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='cajas.cajas')),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetCompras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_comp', models.ForeignKey(db_column='id_comp', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
            ],
            options={
                'db_table': 'det_compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
            ],
            options={
                'db_table': 'productos_x_proveedores',
                'managed': True,
            },
        ),
    ]
