# Generated by Django 5.2.6 on 2025-11-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosxproveedores',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='productosxproveedores',
            name='id_prov',
            field=models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedores'),
        ),
    ]
