# Generated by Django 5.2.6 on 2025-10-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('mitiempo_enloderomi', '0002_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='id_caja',
            field=models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.cajas'),
        ),
        migrations.AddField(
            model_name='detcompras',
            name='id_comp',
            field=models.ForeignKey(db_column='id_comp', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='productosxproveedores',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='productosxproveedores',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='productosxproveedores',
            name='id_prov',
            field=models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedores'),
        ),
    ]
