# Generated by Django 5.2.6 on 2025-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('-compra_fecha', '-compra_hora'), 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_fecha_hora',
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_fecha',
            field=models.DateField(db_index=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_hora',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
