# Generated by Django 5.2.6 on 2025-11-25 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_options_remove_compra_compra_fecha_hora_and_more'),
        ('inventario', '0003_remove_producto_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
    ]
