# Generated by Django 5.2.6 on 2025-11-26 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detalle_compra_producto_alter_detalle_compra_insumo'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor'),
        ),
    ]
