# Generated by Django 5.2.6 on 2025-11-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_empleado_alter_compra_proveedor'),
        ('inventario', '0003_remove_producto_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
