# Generated by Django 5.2.6 on 2025-11-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='egreso_fecha_hora',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='ingreso_fecha_hora',
        ),
        migrations.AddField(
            model_name='egreso',
            name='egreso_fecha',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egreso',
            name='egreso_hora',
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_fecha',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ingreso_hora',
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
    ]
