# Generated by Django 5.2.6 on 2025-11-19 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('compra', '0001_initial'),
        ('servicio', '0001_initial'),
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso por venta/servicio'), ('EGRESO', 'Egreso por compra')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del movimiento (positivo).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(help_text="Descripción del movimiento (e.g., 'Venta #123').", max_length=255)),
                ('caja', models.ForeignKey(help_text='Caja asociada al movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compra.compra')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='servicio.servicio')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='venta.ventas')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
