# Generated by Django 5.2.6 on 2025-11-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja_registro', '0001_initial'),
        ('compra', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compra.compra'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='servicio.servicio'),
        ),
    ]
