# Generated by Django 5.2.6 on 2025-11-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='09:00')),
                ('hora_cierre', models.TimeField(default='18:00')),
                ('dias_abiertos', models.JSONField(blank=True, default=list, help_text="Ej: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado'] (usar minúsculas)")),
                ('tiempo_intervalo', models.PositiveIntegerField(default=30, help_text='Intervalo base entre slots de turnos (en minutos)')),
            ],
            options={
                'verbose_name': 'Configuración del local',
                'verbose_name_plural': 'Configuración del local',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cli', limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_como_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoServicio',
            fields=[
                ('id_turno_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('duracion_servicio', models.PositiveIntegerField(default=30, help_text='Duración en minutos del servicio en este turno')),
                ('servicio', models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Servicio asignado al turno',
                'verbose_name_plural': 'Servicios asignados a los turnos',
                'db_table': 'turnos_x_servicios',
                'unique_together': {('turno', 'servicio')},
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='servicios',
            field=models.ManyToManyField(related_name='turnos', through='turnos.TurnoServicio', to='servicio.servicio'),
        ),
    ]
