# Generated by Django 5.2.5 on 2025-10-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duracion_serv', models.TimeField(blank=True, null=True)),
                ('disponible_serv', models.IntegerField(blank=True, null=True)),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
                ('activado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('estado_turno', models.CharField(blank=True, max_length=9, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cli', models.ForeignKey(db_column='id_cli', limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turnos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TurnosXServicios',
            fields=[
                ('id_turno_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('id_serv', models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.DO_NOTHING, to='turnos.servicios')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.DO_NOTHING, to='turnos.turnos')),
            ],
            options={
                'db_table': 'turnos_x_servicios',
                'managed': True,
            },
        ),
    ]
