# Generated by Django 5.2.6 on 2025-11-26 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicioinsumo_options_and_more'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('fecha_hora_inicio',), name='turno_unico_fecha_hora'),
        ),
    ]
