# Generated by Django 5.2.6 on 2025-11-05 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(db_column='id_cli', on_delete=django.db.models.deletion.CASCADE, related_name='turnos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
