# Generated by Django 5.2.6 on 2025-11-02 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_remove_servicio_duracion_serv_and_more'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(default='09:00')),
                ('hora_cierre', models.TimeField(default='18:00')),
                ('dias_abiertos', models.JSONField(blank=True, default=list, help_text="Ej: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado'] (usar minúsculas)")),
                ('tiempo_intervalo', models.PositiveIntegerField(default=30, help_text='Intervalo base entre slots de turnos (en minutos)')),
            ],
            options={
                'verbose_name': 'Configuración del local',
                'verbose_name_plural': 'Configuración del local',
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha_hora_inicio'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='turnoservicio',
            options={'verbose_name': 'Servicio asignado al turno', 'verbose_name_plural': 'Servicios asignados a los turnos'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='estado_turno',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='servicios_incluidos',
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicios',
            field=models.ManyToManyField(related_name='turnos', through='turnos.TurnoServicio', to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='turnoservicio',
            name='duracion_servicio',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos del servicio en este turno'),
        ),
        migrations.AlterField(
            model_name='turnoservicio',
            name='turno',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='turnos.turno'),
        ),
    ]
