# Generated by Django 5.2.6 on 2025-10-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='disponible_serv',
        ),
        migrations.AddField(
            model_name='turnos',
            name='servicios_incluidos',
            field=models.ManyToManyField(related_name='turnos_relacionados', through='turnos.TurnosXServicios', to='turnos.servicios'),
        ),
    ]
