# Generated by Django 5.2.6 on 2025-10-20 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, choices=[('peluquera', 'Peluquera'), ('manicurista', 'Manicurista'), ('estilista', 'Estilista'), ('multi', 'Múltiple')], help_text='Rol que cumple el profesional en este servicio', max_length=20, null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.servicios')),
            ],
            options={
                'unique_together': {('servicio', 'profesional')},
            },
        ),
    ]
