# Generated by Django 5.2.6 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_turno_unico_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado_pago',
            field=models.CharField(choices=[('no_pagado', 'No pagado'), ('seña', 'Seña recibida'), ('pagado', 'Pago completo')], default='no_pagado', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
