# Generated by Django 5.2.6 on 2025-10-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_remove_servicios_disponible_serv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosxservicios',
            name='id_serv',
            field=models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.CASCADE, to='turnos.servicios'),
        ),
        migrations.AlterField(
            model_name='turnosxservicios',
            name='id_turno',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='turnos.turnos'),
        ),
    ]
