# Generated by Django 5.2.6 on 2025-10-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('turnos', '0003_alter_turnosxservicios_id_serv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='servicios_incluidos',
        ),
        migrations.RemoveField(
            model_name='turnosxservicios',
            name='id_serv',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='id_cli',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='id_prof',
        ),
        migrations.RemoveField(
            model_name='turnosxservicios',
            name='id_turno',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(help_text='Calculado automáticamente al crear/actualizar.')),
                ('estado_turno', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cli', limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(db_column='id_prof', limit_choices_to={'role__in': ['empleado', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_como_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['fecha_hora_inicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TurnoServicio',
            fields=[
                ('id_turno_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Servicio del Turno',
                'verbose_name_plural': 'Servicios del Turno',
                'db_table': 'turnos_x_servicios',
                'managed': True,
                'unique_together': {('turno', 'servicio')},
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='servicios_incluidos',
            field=models.ManyToManyField(related_name='turnos_asociados', through='turnos.TurnoServicio', to='servicio.servicio'),
        ),
        migrations.DeleteModel(
            name='ServicioProfesional',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.DeleteModel(
            name='TurnosXServicios',
        ),
    ]
