# Generated by Django 5.2.6 on 2025-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min_prod', models.IntegerField()),
                ('stock_act_prod', models.IntegerField()),
                ('reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
                ('tipo_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada por compra/reposición'), ('SALIDA', 'Salida por venta/uso'), ('AJUSTE', 'Ajuste manual de inventario')], max_length=10)),
                ('cantidad_movida', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('razon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historiales de Stock',
                'db_table': 'stock_history',
                'managed': False,
            },
        ),
    ]
