<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-30 07:55
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
# Generated by Django 5.2.6 on 2025-11-01 16:40
>>>>>>> 5f5a7856 (Actualizacion de models.py)
=======
# Generated by Django 5.2.6 on 2025-11-04 03:47
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min_prod', models.IntegerField()),
                ('stock_act_prod', models.IntegerField(default=0)),
                ('reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
<<<<<<< HEAD
<<<<<<< HEAD
=======
                ('imagen_url', models.URLField(blank=True, max_length=300, null=True)),
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
                ('imagen_url', models.URLField(blank=True, max_length=300, null=True)),
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada por compra/reposición'), ('SALIDA', 'Salida por venta/uso'), ('AJUSTE', 'Ajuste manual de inventario')], max_length=10)),
                ('cantidad_movida', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('razon', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='productos.productos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historiales de Stock',
                'db_table': 'stock_history',
            },
        ),
    ]
