# Generated by Django 5.2.6 on 2025-11-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_comp', models.IntegerField()),
                ('fecha_hs_comp', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCompras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'det_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_venta', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'det_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'productos_x_proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('tipo_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hs_vent', models.DateTimeField()),
                ('tipo_venta', models.CharField(max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
