# Generated by Django 5.2.6 on 2025-11-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
