# Generated by Django 5.2.6 on 2025-11-03 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('productos', '0001_initial'),
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hs_vent', models.DateTimeField()),
                ('tipo_venta', models.CharField(max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='cajas.cajas')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_venta', models.IntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('id_prod', models.ForeignKey(blank=True, db_column='id_prod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_serv', models.ForeignKey(blank=True, db_column='id_serv', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
        ),
    ]
