# Generated by Django 5.2.6 on 2025-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'verbose_name': 'Detalle de Venta (Producto)', 'verbose_name_plural': 'Detalles de Ventas (Productos)'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-venta_fecha_hora'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
