# Generated by Django 5.2.6 on 2025-11-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_rol_alter_cliente_user'),
        ('ventas', '0002_alter_detalle_venta_options_alter_venta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
        ),
    ]
