# Generated by Django 5.2.6 on 2025-11-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('inventario', '0003_remove_producto_producto_disponible_and_more'),
        ('servicio', '0002_alter_servicioinsumo_options_and_more'),
        ('ventas', '0003_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='detalle_venta_servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='detalle_venta_servicio',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
