<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-04 03:47
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> d8b7e6dc (Arreglé horarios de turnos-cliente)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('tipo_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
    ]
