# Generated by Django 5.2.6 on 2025-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hrs_ape', models.DateTimeField()),
                ('fech_hrs_cie', models.DateTimeField(blank=True, null=True)),
                ('monto_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_caja', models.IntegerField()),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
    ]
