<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# cajas/migrations/0001_initial.py
from django.db import migrations

class Migration(migrations.Migration):
=======
# Generated by Django 5.2.6 on 2025-11-01 16:40
=======
# Generated by Django 5.2.6 on 2025-11-04 03:47
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> d8b7e6dc (Arreglé horarios de turnos-cliente)

from django.db import migrations, models


class Migration(migrations.Migration):

>>>>>>> 5f5a7856 (Actualizacion de models.py)
    initial = True

    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hrs_ape', models.DateTimeField()),
                ('fech_hrs_cie', models.DateTimeField(blank=True, null=True)),
                ('monto_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_caja', models.IntegerField()),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
>>>>>>> 5f5a7856 (Actualizacion de models.py)
    ]
