<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-10 09:02
=======
# Generated by Django 5.2.6 on 2025-11-01 16:40
>>>>>>> 5f5a7856 (Actualizacion de models.py)
=======
# Generated by Django 5.2.6 on 2025-11-04 03:47
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
<<<<<<< HEAD
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hrs_ape', models.DateTimeField()),
                ('fech_hrs_cie', models.DateTimeField(blank=True, null=True)),
                ('monto_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_caja', models.IntegerField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
=======
        migrations.AddField(
            model_name='cajas',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
>>>>>>> 5f5a7856 (Actualizacion de models.py)
        ),
    ]
