<<<<<<< HEAD:backend/mitiempo_django/compras/migrations/0001_initial.py
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-30 07:55

=======
# Generated by Django 5.2.6 on 2025-11-10 09:02
=======
# Generated by Django 5.2.6 on 2025-11-19 13:37
>>>>>>> def20f14 (creacion de caja, movimiento_caja, mod venta mod compra):backend/mitiempo_django/compra/migrations/0001_initial.py

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
# Generated by Django 5.2.6 on 2025-11-01 16:40
=======
# Generated by Django 5.2.6 on 2025-11-04 03:47
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> d8b7e6dc (Arreglé horarios de turnos-cliente)
=======
# Generated by Django 5.2.6 on 2025-11-10 09:02
>>>>>>> a51b6139 (creacion de app compras/proveedores back y front)

import django.core.validators
import django.db.models.deletion
<<<<<<< HEAD
>>>>>>> 5f5a7856 (Actualizacion de models.py)
=======
from decimal import Decimal
from django.conf import settings
>>>>>>> a51b6139 (creacion de app compras/proveedores back y front)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
        ('cajas', '0001_initial'),
>>>>>>> 5f5a7856 (Actualizacion de models.py)
=======
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> a51b6139 (creacion de app compras/proveedores back y front)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='Compras',
=======
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('tipo_prov', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Proveedor')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre_prov'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compra',
>>>>>>> a51b6139 (creacion de app compras/proveedores back y front)
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('id_caja', models.IntegerField(verbose_name='ID Caja')),
                ('fecha_hs_comp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Compra')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('total_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Compra')),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('ro_usuario', models.ForeignKey(db_column='ro_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedores')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'COMPRAS',
                'ordering': ['-fecha_hs_comp'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_um', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'DET_COMPRAS',
            },
        ),
        migrations.CreateModel(
            name='productos_x_proveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
                ('d_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('precio_ultima_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_producto', to='productos.productos')),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.PROTECT, related_name='productos_proveedor', to='compras.proveedores')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedores',
                'db_table': 'productos_x_proveedores',
<<<<<<< HEAD
                'managed': True,
=======
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('tipo_prov', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Proveedor')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre_prov'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('id_caja', models.IntegerField(verbose_name='ID Caja')),
                ('fecha_hs_comp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Compra')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('total_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Compra')),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('ro_usuario', models.ForeignKey(db_column='ro_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compra.proveedores')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'COMPRAS',
                'ordering': ['-fecha_hs_comp'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_um', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra.compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'DET_COMPRAS',
            },
        ),
        migrations.CreateModel(
            name='productos_x_proveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
                ('d_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('precio_ultima_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_producto', to='productos.productos')),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.PROTECT, related_name='productos_proveedor', to='compra.proveedores')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedores',
                'db_table': 'productos_x_proveedores',
                'unique_together': {('id_prod', 'id_prov')},
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
                'unique_together': {('id_prod', 'id_prov')},
>>>>>>> a51b6139 (creacion de app compras/proveedores back y front)
            },
        ),
    ]
