# Generated by Django 5.2.6 on 2025-09-30 06:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apellido_cli', models.CharField(max_length=50)),
                ('correo_cli', models.CharField(max_length=255)),
                ('telefono_cli', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_min_prod', models.IntegerField()),
                ('stock_act_prod', models.IntegerField()),
                ('reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
                ('tipo_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('tipo_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=0, max_digits=9)),
                ('duracion_serv', models.TimeField(blank=True, null=True)),
                ('disponible_serv', models.IntegerField(blank=True, null=True)),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hrs_ape', models.DateTimeField()),
                ('fech_hrs_cie', models.DateTimeField(blank=True, null=True)),
                ('monto_ini', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_egreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_caja', models.IntegerField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_comp', models.IntegerField()),
                ('fecha_hs_comp', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=9)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.cajas')),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetCompras',
            fields=[
                ('id_det_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_comp', models.ForeignKey(db_column='id_comp', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.compras')),
            ],
            options={
                'db_table': 'det_compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id_prod_x_prov', models.AutoField(primary_key=True, serialize=False)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.compras')),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.productos')),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.proveedores')),
            ],
            options={
                'db_table': 'productos_x_proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('estado_turno', models.CharField(blank=True, max_length=9, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cli', models.ForeignKey(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.clientes')),
            ],
            options={
                'db_table': 'turnos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TurnosXServicios',
            fields=[
                ('id_turno_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('id_serv', models.ForeignKey(db_column='id_serv', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.servicios')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.turnos')),
            ],
            options={
                'db_table': 'turnos_x_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fech_hs_vent', models.DateTimeField()),
                ('tipo_venta', models.CharField(max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.clientes')),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.cajas')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_venta', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_prod', models.ForeignKey(blank=True, db_column='id_prod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.productos')),
                ('id_serv', models.ForeignKey(blank=True, db_column='id_serv', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.servicios')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.ventas')),
            ],
            options={
                'db_table': 'det_ventas',
                'managed': True,
            },
        ),
    ]
