# Generated by Django 5.2.6 on 2025-10-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitiempo_enloderomi', '0001_initial'),
        ('productos', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detventas',
            name='id_prod',
            field=models.ForeignKey(blank=True, db_column='id_prod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='detventas',
            name='id_serv',
            field=models.ForeignKey(blank=True, db_column='id_serv', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.clientes'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_caja',
            field=models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.cajas'),
        ),
        migrations.AddField(
            model_name='detventas',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='mitiempo_enloderomi.ventas'),
        ),
    ]
