# Generated by Django 5.2.6 on 2025-10-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitiempo_enloderomi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnosxservicios',
            name='id_serv',
        ),
        migrations.RemoveField(
            model_name='detventas',
            name='id_serv',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='id_cli',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='id_prof',
        ),
        migrations.RemoveField(
            model_name='turnosxservicios',
            name='id_turno',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.DeleteModel(
            name='TurnosXServicios',
        ),
    ]
