# Generated by Django 5.2.6 on 2025-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_direccion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
