# Generated by Django 5.2.6 on 2025-11-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cliente', '0002_remove_cliente_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nombre', 'apellido'), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_telefono',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
