# Generated by Django 5.2.6 on 2025-11-19 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_estado', models.BooleanField(default=True, help_text='True: Abierta, False: Cerrada')),
                ('caja_monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('caja_saldo_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('caja_fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('caja_fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('caja_observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('usuario', models.ForeignKey(help_text="Solo usuarios con rol 'admin' o 'empleado' pueden manejar la caja.", limit_choices_to={'role__in': ['admin', 'empleado']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'constraints': [models.UniqueConstraint(condition=models.Q(('caja_estado', True)), fields=('usuario',), name='unique_caja_abierta_por_usuario')],
            },
        ),
    ]
