# Generated by Django 5.2.6 on 2025-11-22 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(help_text="Solo usuarios con rol 'admin' o 'empleado' pueden manejar la caja.", limit_choices_to={'role__in': ['admin', 'empleado']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('caja_estado', True)), fields=('usuario',), name='unique_caja_abierta_por_usuario'),
        ),
    ]
