<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-11-22 08:17

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.6 on 2025-11-23 04:05

import django.db.models.deletion
>>>>>>> 516c6e32d07084ab8a27435fa8206757c1f490be
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('empleado', '0001_initial'),
>>>>>>> 516c6e32d07084ab8a27435fa8206757c1f490be
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
<<<<<<< HEAD
            name='usuario',
            field=models.ForeignKey(help_text="Solo usuarios con rol 'admin' o 'empleado' pueden manejar la caja.", limit_choices_to={'role__in': ['admin', 'empleado']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('caja_estado', True)), fields=('usuario',), name='unique_caja_abierta_por_usuario'),
=======
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
>>>>>>> 516c6e32d07084ab8a27435fa8206757c1f490be
        ),
    ]
