# Generated by Django 5.2.6 on 2025-11-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_insumo_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo_nombre', models.CharField(max_length=200)),
                ('insumo_unidad', models.CharField(help_text="ej: 'g', 'ml', 'unidad'", max_length=50)),
                ('insumo_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('insumo_stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('insumo_imagen', models.ImageField(blank=True, null=True, upload_to='insumos/')),
                ('insumo_imagen_url', models.TextField(blank=True, null=True)),
                ('categoria_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria_insumo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_disponible', models.BooleanField(default=True)),
                ('producto_fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('producto_imagen_url', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipo_producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto_X_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_insumo_cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad de insumo consumido por unidad de producto', max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto por Insumo',
                'verbose_name_plural': 'Productos por Insumos',
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
