# Generated by Django 5.2.6 on 2025-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_insumo',
            name='activo',
            field=models.BooleanField(default=True, help_text='True = visible/activo, False = oculto/inactivo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(default=True, help_text='True = visible/activo, False = oculto/inactivo'),
        ),
        migrations.AddField(
            model_name='marca',
            name='activo',
            field=models.BooleanField(default=True, help_text='True = visible/activo, False = oculto/inactivo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='True = visible/activo, False = oculto/inactivo'),
        ),
        migrations.AddField(
            model_name='tipo_producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='True = visible/activo, False = oculto/inactivo'),
        ),
        migrations.DeleteModel(
            name='Producto_X_Insumo',
        ),
    ]
