# Generated by Django 5.2.6 on 2025-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_insumo_activo_insumo_activo_marca_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_disponible',
        ),
        migrations.AddField(
            model_name='insumo',
            name='insumo_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
