# Generated by Django 5.2.6 on 2025-11-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria_insumo'),
        ),
    ]
