# Generated by Django 5.2.6 on 2025-11-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(help_text="Categoría del servicio, ej: 'Peluquería', 'Manicura'", max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada del servicio en minutos')),
                ('dias_disponibles', models.JSONField(default=list, help_text="Ej: ['lunes', 'martes', 'miercoles'] (usar minúsculas)")),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
                ('activado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'managed': True,
            },
        ),
    ]
