# Generated by Django 5.2.6 on 2025-11-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada del servicio en minutos.')),
                ('dias_disponibles', models.JSONField(default=list, help_text="Ej: ['lunes', 'martes', 'miercoles']")),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
                ('activado', models.BooleanField(default=True, help_text='True = visible/contratable, False = oculto/inactivo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['nombre_serv'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Insumo por Servicio',
                'verbose_name_plural': 'Insumos por Servicio',
                'unique_together': {('servicio', 'insumo')},
            },
        ),
    ]
