<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-30 07:55
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> parent of def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)
=======
# Generated by Django 5.2.6 on 2025-11-01 16:40
>>>>>>> 5f5a7856 (Actualizacion de models.py)
=======
# Generated by Django 5.2.6 on 2025-11-04 03:47
>>>>>>> 2ccefb3a (recibiendo los ultimos cambios de la rama)
=======
# Generated by Django 5.2.6 on 2025-11-03 17:49
>>>>>>> d8b7e6dc (Arreglé horarios de turnos-cliente)
=======
# Generated by Django 5.2.6 on 2025-11-19 13:37
>>>>>>> def20f14 (creacion de caja, movimiento_caja, mod venta mod compra)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_serv', models.CharField(help_text="Categoría del servicio, ej: 'Peluquería', 'Manicura'", max_length=100)),
                ('nombre_serv', models.CharField(max_length=100)),
                ('precio_serv', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada del servicio en minutos')),
                ('dias_disponibles', models.JSONField(default=list, help_text="Ej: ['lunes', 'martes', 'miercoles'] (usar minúsculas)")),
                ('descripcion_serv', models.TextField(blank=True, null=True)),
                ('activado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'managed': True,
            },
        ),
    ]
