# Generated by Django 5.2.6 on 2025-11-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='id',
            new_name='id_serv',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='tipo',
            new_name='tipo_serv',
        ),
    ]
