# Generated by Django 5.2.6 on 2025-11-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioinsumo',
            options={'verbose_name': 'Insumo por Servicio'},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='activado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id',
            new_name='id_serv',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='tipo',
            new_name='tipo_serv',
        ),
        migrations.RemoveField(
            model_name='servicioinsumo',
            name='cantidad_usada',
        ),
        migrations.AddField(
            model_name='servicioinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_receta', to='servicio.servicio'),
        ),
        migrations.AlterModelTable(
            name='servicioinsumo',
            table='servicioInsumo',
        ),
    ]
