# Generated by Django 5.2.6 on 2025-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_serv',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='rol_requerido',
        ),
        migrations.AddField(
            model_name='servicio',
            name='dias_disponibles',
            field=models.JSONField(default=list, help_text="Ej: ['lunes', 'martes', 'miercoles'] (usar minúsculas)"),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Duración estimada del servicio en minutos'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_serv',
            field=models.CharField(help_text="Categoría del servicio, ej: 'Peluquería', 'Manicura'", max_length=100),
        ),
        migrations.DeleteModel(
            name='ServicioProfesional',
        ),
    ]
