# Generated by Django 5.2.6 on 2025-11-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_rename_id_servicio_id_serv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='activado',
            new_name='activo',
        ),
    ]
